I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 20, in script call
    call scene_2
  File "game/story/Act2/scene_2.rpy", line 26, in script
    aditi determined "It’s here, huh?"
Exception: Say has image attributes ('determined',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script call
    call scene_2
  File "game/story/Act2/scene_2.rpy", line 26, in script
    aditi determined "It’s here, huh?"
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\exports.py", line 1473, in say
    who(what, *args, **kwargs)
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1290, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1109, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\akank\OneDrive\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1035, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('determined',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Echoes Beyond The Gate 1.0
Thu Nov  9 19:15:27 2023
